### ISSUE TITLE
paper regarding BINARY

### ISSUE THREAD

**Issue by 0225yyyyyqq** [senlin-lin/BINARY#1]
Please can I read your paper, regarding BINARY, I can't find it. Thank you very much

**Comment by senlin-lin** [comment]
Thank you for your interest in our work! While the final version of our paper regarding BINARY isn't available yet, we have a preprint version uploaded on bioRxiv. You can access it via this link: https://doi.org/10.1101/2023.10.15.562443.

It's worth noting that the final version of our paper will include significant additional content and enhancements beyond what is presented in the preprint. We are currently in the process of finalizing and polishing the paper for publication, and we anticipate that the detailed and final version will be available online soon. Please stay tuned for updates!

**Comment by senlin-lin** [comment]
Thank you for your interest in our work! While the final version of our paper regarding BINARY isn't available yet, we have a preprint version uploaded on bioRxiv. You can access it via this link: https://doi.org/10.1101/2023.10.15.562443.

It's worth noting that the final version of our paper will include significant additional content and enhancements beyond what is presented in the preprint. We are currently in the process of finalizing and polishing the paper for publication, and we anticipate that the detailed and final version will be available online soon. Please stay tuned for updates!
